### PR TITLE
Add ya nasim al ward

### PR DESCRIPTION
**Pull request by thenotepadwriter**

### CODE REVIEW

**Review by adehad — APPROVED** [review]
MashAllah.
Jummah Mubarak wa Jazakun Allah Khayr

(as part of review checked with this recording: https://www.youtube.com/watch?v=jlFPcqDmKAY)

**Comment by thenotepadwriter** [comment]
> MashAllah.
> Jummah Mubarak wa Jazakun Allah Khayr
> 
> (as part of review checked with this recording: https://www.youtube.com/watch?v=jlFPcqDmKAY)

Alhamdulillah, barak Allah fekum 🤲

**Comment by adehad** [comment]
(Pg 107 from Song of Presence was sung today)

**Comment by thenotepadwriter** [comment]
> (Pg 107 from Song of Presence was sung today)

Oh, great, I hadn't checked it! Can update isA if we want?

**Comment by adehad** [comment]
> > (Pg 107 from Song of Presence was sung today)
> 
> Oh, great, I hadn't checked it! Can update isA if we want?

Yeah I think InshAllah that would be good! I'll make a branch we can both use

**Pull request merged**
